AppPeluditos/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from AppPeluditos import views
from rest_framework import routers
from .views import ProductoViewset

router = routers.DefaultRouter()
router.register('producto',ProductoViewset)



urlpatterns = [
   
    path('',views.home, name='Home'),
    path('Somos',views.somos, name='Somos'),
    path('hacemos',views.hacemos, name='Hacemos'),
    path('contacto',views.contacto, name='Contacto'),
    path('registro/',views.registro, name='Registro'),
    path('tienda',views.tienda, name='Tienda'),
    path('agregar', views.agregar, name='Agregar'),
    path('modificar/<id>/', views.modificar, name='Modificar'), 
    path('eliminar/<id>/', views.eliminar, name='Eliminar'),

    path('reset_password/', auth_views.PasswordResetView.as_view(), name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_don"),

    path('reset/<uid64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),

    path('api/',include(router.urls)),


] 

ProyectoPeluditos/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('',include('AppPeluditos.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('',include('pwa.urls')), 

]

static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppPeluditos/models.py
from django.db import models

# Create your models here.

class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    correo = models.CharField(max_length=50)
    asunto = models.CharField(max_length=50)
    mensaje = models.CharField(max_length=500)

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to="productos", null=True)
    def __str__(self):
        return self.nombre

AppPeluditos/forms.py
from django import forms
from .models import Contacto, Producto
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ContactoForm(forms.ModelForm):

    class Meta:
            model = Contacto
            fields = ["nombre","apellido","correo","asunto","mensaje"]

            
class CustomUserCreationForm(UserCreationForm):

        class Meta:
            model = User
            fields = ['username', "first_name", "last_name", "email", "password1", "password2"]
    

class ProductoForm(forms.ModelForm):

    class Meta:
        model = Producto
        fields = '__all__'

    

AppPeluditos/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .forms import ContactoForm, CustomUserCreationForm, ProductoForm
from django.contrib import messages
from django.contrib.auth import authenticate,login
from django.http import Http404  
from .models import Producto
from django.db.models import Q
from rest_framework import viewsets
from .serializers import ProductoSerializer

# Create your views here.



class ProductoViewset(viewsets.ModelViewSet):
    queryset = Producto.objects.all()
    serializer_class = ProductoSerializer


    def get_queryset(self):
        productos = Producto.objects.all()

        nombre = self.request.GET.get('nombre')

        if nombre:
            productos = productos.filter(nombre__contains=nombre)

        return productos




def home(request):
   
    return render(request,"AppPeluditos/home.html")

def somos(request):

    return render(request,"AppPeluditos/somos.html")

def hacemos(request):

    return render(request,"AppPeluditos/hacemos.html")

def contacto(request):
    data = {
            'form': ContactoForm()
    }

    if request.method == 'POST':
        formulario = ContactoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Te contactaremos pronto!")
        else:
                data["form"] = formulario
    return render(request,"AppPeluditos/contacto.html",data)

def registro(request):
    data = {
        'form': CustomUserCreationForm()
    }

    if request.method == 'POST':
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"] , password=formulario.cleaned_data["password1"])
            login(request, user)
            messages.success(request, "Usuario registrado correctamente")
            return redirect(to="Home")
        data["form"] = formulario

    return render(request, 'registration/registro.html', data)



def tienda(request):
    busqueda = request.GET.get("buscar")
    productos = Producto.objects.all()
    if busqueda:
        productos = Producto.objects.filter(
            Q(nombre__icontains = busqueda)
        ).distinct()
    data = {
        'productos': productos
    }

    
    
    return render(request,"AppPeluditos/tienda.html", data)

def agregar(request):

    data = {
        'form': ProductoForm()
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Producto agregrado correctamente")
            return redirect(to="Tienda")
        else:
            data["form"] = formulario   
    return render (request,"AppPeluditos/agregar.html", data)    


def modificar(request, id):
    
    producto = get_object_or_404(Producto, id=id)

    data = {
        'form': ProductoForm(instance=producto)
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, instance=producto, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Producto modificado correctamente")
            return redirect(to="Tienda")
        data["form"] = formulario    

    return render (request, "AppPeluditos/modificar.html", data)

def eliminar(request, id):
    producto = get_object_or_404(Producto, id=id)
    producto.delete()
    messages.success(request, "Producto eliminado correctamente")
    return redirect(to="Tienda")

AppPeluditos/templates/AppPeluditos/agregar.html
<!doctype html>
<html lang="en">
  <head>

    {% load static %}
     <!--sweet alerts-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href=" https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css " integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

        <!--link del estilo -->
    <link rel="stylesheet" href="{% static 'AppPeluditos/css/estilos.css' %}">
    <title>Fundación Peluditos</title>
  </head>
  <body>
      
    <!--nav bar de bootstrap :)-->

    <nav class="navbar navbar-expand-lg navbar-dark fixed-top sps sps--abv">
        <div class="container">
        <a class="navbar-brand" href="{% url 'Home' %}">
            <img class="logo" src="{% static 'AppPeluditos/img/peluditosazul.png' %}" alt="logo">
        </a>
           
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Somos' %}" >¿Quienes somos?</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Hacemos' %}" target="_blank">¿Que hacemos?</a>
              </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                ¿Como ayudar?
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Adopta</a>
                <a class="dropdown-item" href="{% url 'Tienda' %}">Tienda</a>
                <a class="dropdown-item" href="#">Haz tu donación</a>
              </div>
            </li>
            <!-- AGREGAR DESPUES
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Adopta!
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">La importancia de adoptar</a>
                  <a class="dropdown-item" href="#">10 razones de por qué adoptar</a>
                  <a class="dropdown-item" href="#">Peluditos en adopción</a>
                </div>
              </li>
              -->

              <li class="nav-item">
                <a class="nav-link" href="{% url 'Contacto' %}" target="_blank">Contacto</a>
              </li>

              <li>
                  <img class="iconos-redes" src="{% static 'AppPeluditos/iconos/facebook-logo-button.svg' %}" alt="face">
                  <img class="iconos-redes" src="{% static 'AppPeluditos/iconos/instagram-logo.svg' %}" alt="instagram">
                  <img class="iconos-redes" src="{% static 'AppPeluditos/iconos/twitter-logo-button.svg' %}" alt="twitter">
              </li>
              {% if user.is_authenticated %}
              <li>
                <a href="{%url 'logout' %}" style="padding-right: 10px; color:#000000;">Cerrar sesion</a>

              </li>
              |
              <li>
                  <a href="#" style="padding-left: 10px; color:#000000">@{{user.username}}</a>
              </li>
              {% else %}
              <li>
                  <a href="{% url 'login' %}" style="padding-right: 8px; color:#000000" >Iniciar sesion</style></a>
                  
              |     
              </li>
              
              <li>
                
                <a href="{% url 'Registro' %}" style="padding-left: 10px; color:#000000;">Registrate!</a>
              </li>
            {% endif %}
           
          </ul>
          </div>
         </div> <!--fin del container-->
    </nav>
    <main>
      {% load crispy_forms_tags %}

                <h2 class="agregar">Agregar producto</h2>
                <div class="roww">
                    <div class="col-12 col md-6 offset-md-3">
                        <div class="card">
                            <div class="card-body">

                         <form action="" method="post" enctype="multipart/form-data">

                            {% csrf_token %}
                            {{ form | crispy }}

                            <div class="d-flex justify-content-end">
                                <input type="reset" value="Cancelar" class="btn btn-secondary">
                                &nbsp;
                                <input type="submit" value="Guardar" class="btn btn-primary">   
                            </div>
                            


                         </form>
                            {% if messages %}
                            {% for m in messages %}
                            <script>
                                Swal.fire({
                                    "title": "Felicitaciones",
                                    "text": "{{m}}",
                                    "icon":"success"
                                })
                            </script>
                            {% endfor %}
                            {% endif %}  

                         
                             </div>
                        </div>

                    </div>
                </div> 


    </main>
    

    <footer>
        <img class="logo-footer" src="{% static 'AppPeluditos/img/peluditosflooter.png' %}" alt="logo">
        <br>

        <img class="iconos-redes" src="{% static 'AppPeluditos/iconos/facebook-logo-button.svg' %}" alt="face">
        <img class="iconos-redes" src="{% static 'AppPeluditos/iconos/instagram-logo.svg' %}" alt="instagram">
        <img class="iconos-redes" src="{% static 'AppPeluditos/iconos/twitter-logo-button.svg' %}" alt="twitter">

        <p>Derechos reservados Fundación Peluditos® 2020</p>

</footer>






<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>


<!--menu scroll peluditos-->
<script src="{% static 'AppPeluditos/js/js_scrollPosStyler.min.js' %}"></script>

</body>
</html>

AppPeluditos/templates/AppPeluditos/tienda.html
<!doctype html>
<html lang="en">
  <head>

    {% load static %}

    <script>
      function eliminarProducto(id){
        Swal.fire({
            "title":"¿Estás seguro?",
            "text":"Esta acción no se puede deshacer",
            "icon":"question",
            "showCancelButton":true,
            "cancelButtonText":"No, Cancelar",
            "confirmButtonText":"Si, Eliminar",
            "reverseButtons:":true,
            "confirmButtonColor":"#dc3545"
        })
        .then(function(result) {
            if(result.isConfirmed){
                window.location.href = "/eliminar/"+id+"/"
            }
        })
      }
    </script>
     <!--sweet alerts-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href=" https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css " integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

        <!--link del estilo -->
    <link rel="stylesheet" href="{% static 'AppPeluditos/css/estilos.css' %}">
    <title>Fundación Peluditos</title>
  </head>
  <body>
      
    <!--nav bar de bootstrap :)-->

    <nav class="navbar navbar-expand-lg navbar-dark fixed-top sps sps--abv">
        <div class="container">
        <a class="navbar-brand" href="{% url 'Home' %}">
            <img class="logo" src="{% static 'AppPeluditos/img/peluditosazul.png' %}" alt="logo">
        </a>
           
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Somos' %}" >¿Quienes somos?</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Hacemos' %}" target="_blank">¿Que hacemos?</a>
              </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                ¿Como ayudar?
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Adopta</a>
                <a class="dropdown-item" href="{% url 'Tienda' %}">Tienda</a>
                <a class="dropdown-item" href="#">Haz tu donación</a>
              </div>
            </li>
            <!-- AGREGAR DESPUES
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Adopta!
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">La importancia de adoptar</a>
                  <a class="dropdown-item" href="#">10 razones de por qué adoptar</a>
                  <a class="dropdown-item" href="#">Peluditos en adopción</a>
                </div>
              </li>
              -->

              <li class="nav-item">
                <a class="nav-link" href="{% url 'Contacto' %}" target="_blank">Contacto</a>
              </li>

              <li>
                  <img class="iconos-redes" src="{% static 'AppPeluditos/iconos/facebook-logo-button.svg' %}" alt="face">
                  <img class="iconos-redes" src="{% static 'AppPeluditos/iconos/instagram-logo.svg' %}" alt="instagram">
                  <img class="iconos-redes" src="{% static 'AppPeluditos/iconos/twitter-logo-button.svg' %}" alt="twitter">
              </li>
              {% if user.is_authenticated %}
              <li>
                <a href="{%url 'logout' %}" style="padding-right: 10px; color:#000000;">Cerrar sesion</a>

              </li>
              |
              <li>
                  <a href="#" style="padding-left: 10px; color:#000000">@{{user.username}}</a>
              </li>
              {% else %}
              <li>
                  <a href="{% url 'login' %}" style="padding-right: 8px; color:#000000" >Iniciar sesion</style></a>
                  
              |     
              </li>
              
              <li>
                
                <a class="registrate" href="{% url 'Registro' %}" style="padding-left: 20px; color:#000000;">Registrate!</a>
              </li>
            {% endif %}
           
          </ul>
          </div>
         </div> <!--fin del container-->
    </nav>
    <main>
      <section>
        <h2 class="tituloP">Tienda Peluditos!</h2>
        
        <h4 class="textopeluditos">En conjunto con petshop peluditos, 
          hemos creado esta tienda, por si quieres apoyar a nuestros peluditos comprando cositas 
          para tu amiguito!
        </h4>
        <td>
          {% if perms.AppPeluditos.add_producto %}
          <div>
          <a href="{% url 'Agregar' %}" class="btn-info btn-sm botonagregar">Agregar Producto</a>
          <hr>
          </div>
          {% endif %}
        </td>
          {% load humanize %}

          <!--BUSCADOR-->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
            method="GET">
              {% csrf_token %}
              <div class="input-group">
                <input type="text" class="form-control bg-light border-0 small" placeholder="Buscar..." name="buscar" value="">
                <div class="input-group-append">
                  <button class="btn btn-primary buton" type="submit">
                    <i class="fas fa-search fa-sm"></i>
                  </button>
                </div>
              </div>
          </form>

          <div class="row">
            {% for p in productos %}

                <div class="col-md-3 col-sm-12 col-lg-4">
                  <div class="card card1" style="width: 80%; text-align: center;">
                    <img src="{{ p.imagen.url }}" style="width:50%" class="card-img-top imagen" alt="{{ producto.nombre}}">
                    <div class="card-body">
                        <h5 class="card-title">{{ p.nombre | title}} </h5>
                        <p class="card-text">${{ p.precio | intcomma }}</p>
                        <p class="card-text">{{ p.descripcion | capfirst }}</p>
                    </div>
                    <div class="card-footer text-center">
                      {% if perms.AppPeluditos.change_producto %}
                      <a href="{% url 'Modificar' p.id %}" class="btn btn-info btn-sm btnmodificar">Modificar</a>
                        {% endif %}
                      &nbsp;
                        {% if perms.AppPeluditos.delete_producto %}
                      <a href="#" onclick="eliminarProducto({{ p.id }})" class="btn btn-danger btn-sm btneliminar">Eliminar</a>
                        {% endif %} 
                         
                    </div>
                    

                  </div>

                </div>

            {% endfor %}

          </div>



           
          </div>
                      {% if messages %}
                            {% for m in messages %}
                            <script>
                                Swal.fire({
                                    "title": "Felicitaciones",
                                    "text": "{{m}}",
                                    "icon":"success"
                                })
                            </script>
                            {% endfor %}
                            {% endif %}  
      </section>    
    </main>
    

    <footer>
        <img class="logo-footer" src="{% static 'AppPeluditos/img/peluditosflooter.png' %}" alt="logo">
        <br>

        <img class="iconos-redes" src="{% static 'AppPeluditos/iconos/facebook-logo-button.svg' %}" alt="face">
        <img class="iconos-redes" src="{% static 'AppPeluditos/iconos/instagram-logo.svg' %}" alt="instagram">
        <img class="iconos-redes" src="{% static 'AppPeluditos/iconos/twitter-logo-button.svg' %}" alt="twitter">

        <p>Derechos reservados Fundación Peluditos® 2020</p>

</footer>






<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>


<!--menu scroll peluditos-->
<script src="{% static 'AppPeluditos/js/js_scrollPosStyler.min.js' %}"></script>

</body>
</html>